import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { Oxanium } from "next/font/google";

export const metadata: Metadata = {
	title: "V3 Workout Tracker",
	description: "Generated by create next app",
};

const oxanium = Oxanium({
	subsets: ["latin"],
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={oxanium.className}
			suppressHydrationWarning>
			<body>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange>
					<main className="flex flex-col w-full h-dvh align-center">
						{children}
					</main>
				</ThemeProvider>
			</body>
		</html>
	);
}
