export const DEFAULT_EXERCISES: { id: string; name: string }[] = [
	{ id: "default-1", name: "Bench Press" },
	{ id: "default-2", name: "Squat" },
	{ id: "default-3", name: "Deadlift" },
	{ id: "default-4", name: "Pull Up" },
	{ id: "default-5", name: "Overhead Press" },
	{ id: "default-6", name: "Dumbbell Bench Press" },
	{ id: "default-7", name: "Incline Bench Press" },
	{ id: "default-8", name: "Barbell Row" },
	{ id: "default-9", name: "Dumbbell Row" },
	{ id: "default-10", name: "Lat Pulldown" },
	{ id: "default-11", name: "Leg Press" },
	{ id: "default-12", name: "Lunges" },
	{ id: "default-13", name: "Romanian Deadlift" },
	{ id: "default-14", name: "Leg Curl" },
	{ id: "default-15", name: "Leg Extension" },
	{ id: "default-16", name: "Calf Raise" },
	{ id: "default-17", name: "Lateral Raise" },
	{ id: "default-18", name: "Front Raise" },
	{ id: "default-19", name: "Bicep Curl" },
	{ id: "default-20", name: "Preacher Curl" },
	{ id: "default-21", name: "Tricep Extension" },
	{ id: "default-22", name: "Tricep Pushdown" },
	{ id: "default-23", name: "Cable Crunches" },
	{ id: "default-24", name: "Cable Flyes" },
	{ id: "default-25", name: "Seated Cable Row" },
	{ id: "default-26", name: "Upright Row" },
	{ id: "default-27", name: "Shrugs" },
	{ id: "default-28", name: "Dips" },
	{ id: "default-29", name: "Assisted Dips" },
	{ id: "default-30", name: "Assisted Pullups" },
	{ id: "default-31", name: "Bulgarian Split Squat" },
	{ id: "default-32", name: "Split Squat" },
	{ id: "default-33", name: "Back Extension" },
];
