export const DEFAULT_EXERCISES: {
	id: string;
	name: string;
	muscleGroups: string[];
}[] = [
	{ id: "default-1", name: "Bench Press", muscleGroups: ["chest"] },
	{ id: "default-2", name: "Squat", muscleGroups: ["quadriceps"] },
	{ id: "default-3", name: "Deadlift", muscleGroups: ["lower back"] },
	{ id: "default-4", name: "Pull Up", muscleGroups: ["lats"] },
	{ id: "default-5", name: "Overhead Press", muscleGroups: ["deltoids"] },
	{ id: "default-6", name: "Dumbbell Bench Press", muscleGroups: ["chest"], },
	{ id: "default-7", name: "Incline Bench Press", muscleGroups: ["upper chest"], },
	{ id: "default-8", name: "Barbell Row", muscleGroups: ["upper back"] },
	{ id: "default-9", name: "Dumbbell Row", muscleGroups: ["upper back"] },
	{ id: "default-10", name: "Lat Pulldown", muscleGroups: ["lats"] },
	{ id: "default-11", name: "Leg Press", muscleGroups: ["quadriceps"] },
	{ id: "default-12", name: "Lunges", muscleGroups: ["quadriceps"] },
	{ id: "default-13", name: "Romanian Deadlift", muscleGroups: ["hamstrings"], },
	{ id: "default-14", name: "Leg Curl", muscleGroups: ["hamstrings"] },
	{ id: "default-15", name: "Leg Extension", muscleGroups: ["quadriceps"], },
	{ id: "default-16", name: "Calf Raise", muscleGroups: ["calves"] },
	{ id: "default-17", name: "Lateral Raise", muscleGroups: ["deltoids"] },
	{ id: "default-18", name: "Front Raise", muscleGroups: ["deltoids"] },
	{ id: "default-19", name: "Bicep Curl", muscleGroups: ["biceps"] },
	{ id: "default-20", name: "Preacher Curl", muscleGroups: ["biceps"] },
	{ id: "default-21", name: "Tricep Extension", muscleGroups: ["triceps"], },
	{ id: "default-22", name: "Tricep Pushdown", muscleGroups: ["triceps"], },
	{ id: "default-23", name: "Cable Crunches", muscleGroups: ["abdominals"], },
	{ id: "default-24", name: "Cable Flyes", muscleGroups: ["chest"] },
	{ id: "default-25", name: "Seated Cable Row", muscleGroups: ["upper back"], },
	{ id: "default-26", name: "Upright Row", muscleGroups: ["trapezius"] },
	{ id: "default-27", name: "Shrugs", muscleGroups: ["trapezius"] },
	{ id: "default-28", name: "Dips", muscleGroups: ["triceps"] },
	{ id: "default-29", name: "Assisted Dips", muscleGroups: ["triceps"] },
	{ id: "default-30", name: "Assisted Pullups", muscleGroups: ["lats"] },
	{ id: "default-31", name: "Bulgarian Split Squat", muscleGroups: ["quadriceps"], },
	{ id: "default-32", name: "Split Squat", muscleGroups: ["quadriceps"] },
	{ id: "default-33", name: "Back Extension", muscleGroups: ["lower back"], },
];
