export const DEFAULT_EXERCISES: {
	id: string;
	name: string;
	muscleGroups: string[];
}[] = [
	{ id: "default-1", name: "Assisted Dips", muscleGroups: ["triceps", "chest"] },
	{ id: "default-2", name: "Assisted Pullups", muscleGroups: ["lats"] },
	{ id: "default-3", name: "Back Extension", muscleGroups: ["lower back", "hamstrings"] },
	{ id: "default-4", name: "Barbell Row", muscleGroups: ["upper back"] },
	{ id: "default-5", name: "Bench Press", muscleGroups: ["chest"] },
	{ id: "default-6", name: "Bicep Curls", muscleGroups: ["biceps"] },
	{
		id: "default-7",
		name: "Bulgarian Split Squat",
		muscleGroups: ["quadriceps", "gluteus maximus"],
	},
	{ id: "default-8", name: "Cable Crunches", muscleGroups: ["abdominals"] },
	{ id: "default-9", name: "Cable Flyes", muscleGroups: ["chest"] },
	{ id: "default-10", name: "Cable Lateral Raises", muscleGroups: ["deltoids"] },
	{ id: "default-11", name: "Calf Raises", muscleGroups: ["calves"] },
	{ id: "default-12", name: "Dumbbell Bench Press", muscleGroups: ["chest"] },
	{ id: "default-13", name: "Hamstring Curls", muscleGroups: ["hamstrings"] },
	{ id: "default-14", name: "Hip Abductor Machine", muscleGroups: ["gluteus maximus"] },
	{ id: "default-15", name: "Hip Adductor Machine", muscleGroups: ["quadriceps"] },
	{ id: "default-16", name: "Incline Bench Press", muscleGroups: ["upper chest"] },
	{ id: "default-17", name: "Incline Curls", muscleGroups: ["biceps"] },
	{ id: "default-18", name: "Lat Pulldown", muscleGroups: ["lats"] },
	{ id: "default-19", name: "Lateral Raises", muscleGroups: ["deltoids"] },
	{ id: "default-20", name: "Leg Extension", muscleGroups: ["quadriceps"] },
	{ id: "default-21", name: "Leg Press", muscleGroups: ["quadriceps", "gluteus maximus"] },
	{ id: "default-22", name: "Machine Press", muscleGroups: ["chest"] },
	{ id: "default-23", name: "Machine Row", muscleGroups: ["upper back"] },
	{ id: "default-24", name: "Machine Shoulder Press", muscleGroups: ["deltoids", "triceps"] },
	{
		id: "default-25",
		name: "One-arm Cable Rear Delt Flyes",
		muscleGroups: ["deltoids"],
	},
	{ id: "default-26", name: "Overhead Press", muscleGroups: ["deltoids", "triceps"] },
	{ id: "default-27", name: "Overhead Tricep Extensions", muscleGroups: ["triceps"] },
	{ id: "default-28", name: "Pec Deck", muscleGroups: ["chest"] },
	{ id: "default-29", name: "Pectoral", muscleGroups: ["chest"] },
	{ id: "default-30", name: "Preacher Curls", muscleGroups: ["biceps"] },
	{ id: "default-31", name: "Pullups", muscleGroups: ["lats"] },
	{ id: "default-32", name: "Reverse Dumbbell Flyes", muscleGroups: ["deltoids"] },
	{ id: "default-33", name: "Reverse Pec Deck", muscleGroups: ["deltoids"] },
	{ id: "default-34", name: "Romanian Deadlift", muscleGroups: ["hamstrings", "lower back"] },
	{ id: "default-35", name: "Seated Cable Row", muscleGroups: ["upper back"] },
	{ id: "default-36", name: "Shrugs", muscleGroups: ["trapezius"] },
	{ id: "default-37", name: "Tricep Pushdowns", muscleGroups: ["triceps"] },
	{ id: "default-38", name: "Upright Row", muscleGroups: ["trapezius", "deltoids"] },
	{ id: "default-39", name: "Squat", muscleGroups: ["quadriceps", "gluteus maximus"] },
	{
		id: "default-40",
		name: "Deadlift",
		muscleGroups: ["lower back", "hamstrings", "gluteus maximus"],
	},
	{ id: "default-41", name: "Dumbbell Rows", muscleGroups: ["upper back"] },
	{ id: "default-42", name: "Front Raises", muscleGroups: ["deltoids"] },
	{ id: "default-43", name: "Dips", muscleGroups: ["triceps", "chest"] },
];
